source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

gem 'oauth'
gem 'twitter'

gem 'rspec'
gem 'sidekiq'
gem "redis", "~> 3.0.4"

ruby '1.9.3'
